In [221]:
import numpy as np
import pandas as pd

In [222]:
poll_data = pd.read_excel('AC105_2014.xlsx')

In [223]:
poll_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 28 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Polling Station No.                  237 non-null    object
 1   ELANGOVAN.E.V.K.S                    237 non-null    object
 2   GURUSAMY.N                           237 non-null    object
 3   SATHYABAMA.V                         237 non-null    object
 4   SUBBARAYAN.K                         237 non-null    object
 5   SENTHILNATHAN.M                      237 non-null    object
 6   DINESHKUMAR.N                        237 non-null    object
 7   GOPALSAMY.R                          237 non-null    object
 8   CHAKRAVARTHI RAJA GOPALA KRISHNAN.R  237 non-null    object
 9   SIVAKUMAR.N                          237 non-null    object
 10  MURUGESAN.R                          237 non-null    object
 11  LAXMI.J                              237 non-null    object
 12  SATHYABAMA.R                         237 non-null    object
 13  SATHYABHAMA.R                        237 non-null    object
 14  SENTHILKUMAR.K                       237 non-null    object
 15  SENTHIL KUMAR.T.S                    237 non-null    object
 16  SELVABOOPATHI.P                      237 non-null    object
 17  DINESHKUMAR.S.K                      237 non-null    object
 18  NANDHAKUMAR.R                        237 non-null    object
 19  PALANISAMY.M                         237 non-null    object
 20  BALASUBRAMANIYAN. P                  237 non-null    object
 21  PONNUSAMY.A                          237 non-null    object
 22  MURUGAN.R.R                          237 non-null    object
 23  MOGHEETH KHAN.A                      237 non-null    object
 24  RAJENDRAN.M                          237 non-null    object
 25  PASTOR JAMES.A                       237 non-null    object
 26  SHEIKDAVOOD.A.M                      237 non-null    object
 27  NOTA                                 237 non-null    object
dtypes: object(28)
memory usage: 52.0+ KB

In [224]:
poll_data.shape

(237, 28)

In [225]:
poll_data.head()

   Polling Station No.         ELANGOVAN.E.V.K.S  ... SHEIKDAVOOD.A.M  NOTA
0  Polling Station No.  INDIAN NATIONAL CONGRESS  ...     INDEPENDENT  NOTA
1                    1                        19  ...               1     2
2                    2                        39  ...               3     3
3                    3                         9  ...               0     4
4                    4                        18  ...               3    10

[5 rows x 28 columns]

In [226]:
poll_data.columns

Index(['Polling Station No.', 'ELANGOVAN.E.V.K.S', 'GURUSAMY.N',
       'SATHYABAMA.V', 'SUBBARAYAN.K', 'SENTHILNATHAN.M', 'DINESHKUMAR.N',
       'GOPALSAMY.R', 'CHAKRAVARTHI RAJA GOPALA KRISHNAN.R', 'SIVAKUMAR.N',
       'MURUGESAN.R', 'LAXMI.J', 'SATHYABAMA.R', 'SATHYABHAMA.R',
       'SENTHILKUMAR.K', 'SENTHIL KUMAR.T.S', 'SELVABOOPATHI.P',
       'DINESHKUMAR.S.K', 'NANDHAKUMAR.R', 'PALANISAMY.M',
       'BALASUBRAMANIYAN. P', 'PONNUSAMY.A', 'MURUGAN.R.R', 'MOGHEETH KHAN.A',
       'RAJENDRAN.M', 'PASTOR JAMES.A', 'SHEIKDAVOOD.A.M', 'NOTA'],
      dtype='object')

In [227]:
poll_data.rename(columns={'Polling Station No.':'Candidate'}, inplace=True)

In [228]:
poll_data.set_index('Candidate')

                            ELANGOVAN.E.V.K.S  ...  NOTA
Candidate                                      ...
Polling Station No.  INDIAN NATIONAL CONGRESS  ...  NOTA
1                                          19  ...     2
2                                          39  ...     3
3                                           9  ...     4
4                                          18  ...    10
...                                       ...  ...   ...
232                                        16  ...     4
233                                        21  ...    11
234                                        24  ...     2
235                                        18  ...     5
236                                       136  ...    19

[237 rows x 27 columns]

In [229]:
poll_data.shape

(237, 28)

In [230]:
poll_data = poll_data.transpose()

In [231]:
poll_data.head()

                                                        0    1    ...  235  236
Candidate                               Polling Station No.    1  ...  235  236
ELANGOVAN.E.V.K.S                  INDIAN NATIONAL CONGRESS   19  ...   18  136
GURUSAMY.N                              BAHUJAN SAMAJ PARTY   14  ...    4    8
SATHYABAMA.V       ALL INDIA ANNA DRAVIDA MUNNETRA KAZHAGAM  335  ...  296  441
SUBBARAYAN.K                       COMMUNIST PARTY OF INDIA   12  ...    2    2

[5 rows x 237 columns]

In [232]:
new_header = poll_data.iloc[0] 

poll_data = poll_data[1:] 

poll_data.columns = new_header

In [233]:
poll_data.head()

Candidate                               Polling Station No.    1  ...  235  236
ELANGOVAN.E.V.K.S                  INDIAN NATIONAL CONGRESS   19  ...   18  136
GURUSAMY.N                              BAHUJAN SAMAJ PARTY   14  ...    4    8
SATHYABAMA.V       ALL INDIA ANNA DRAVIDA MUNNETRA KAZHAGAM  335  ...  296  441
SUBBARAYAN.K                       COMMUNIST PARTY OF INDIA   12  ...    2    2
SENTHILNATHAN.M                   DRAVIDA MUNNETRA KAZHAGAM  337  ...  139  233

[5 rows x 237 columns]

In [234]:
poll_data.shape

(27, 237)

In [235]:
poll_data.to_excel('poll_data_lform.xlsx')

In [236]:
poll_data.reset_index(inplace=True)

In [237]:
poll_data.rename(columns={'index':'candidate'}, inplace=True)

In [238]:
poll_data.head()

Candidate          candidate  ...  236
0          ELANGOVAN.E.V.K.S  ...  136
1                 GURUSAMY.N  ...    8
2               SATHYABAMA.V  ...  441
3               SUBBARAYAN.K  ...    2
4            SENTHILNATHAN.M  ...  233

[5 rows x 238 columns]

In [240]:
#poll_data.drop('Candidate',axis=1,inplace = True)

In [241]:
poll_data.head()

Candidate          candidate  ...  236
0          ELANGOVAN.E.V.K.S  ...  136
1                 GURUSAMY.N  ...    8
2               SATHYABAMA.V  ...  441
3               SUBBARAYAN.K  ...    2
4            SENTHILNATHAN.M  ...  233

[5 rows x 238 columns]

In [242]:
poll_data.rename_axis(None, inplace=True)

In [243]:
poll_data.columns

Index([          'candidate', 'Polling Station No.',                     1,
                           2,                     3,                     4,
                           5,                     6,                     7,
                           8,
       ...
                         227,                   228,                   229,
                         230,                   231,                   232,
                         233,                   234,                   235,
                         236],
      dtype='object', name='Candidate', length=238)

In [244]:
poll_data.head()

Candidate          candidate  ...  236
0          ELANGOVAN.E.V.K.S  ...  136
1                 GURUSAMY.N  ...    8
2               SATHYABAMA.V  ...  441
3               SUBBARAYAN.K  ...    2
4            SENTHILNATHAN.M  ...  233

[5 rows x 238 columns]

In [245]:
poll_data.rename(columns={'Polling Station No.':'party'}, inplace=True)

In [246]:
poll_data.head()

Candidate          candidate  ...  236
0          ELANGOVAN.E.V.K.S  ...  136
1                 GURUSAMY.N  ...    8
2               SATHYABAMA.V  ...  441
3               SUBBARAYAN.K  ...    2
4            SENTHILNATHAN.M  ...  233

[5 rows x 238 columns]

In [247]:
poll_data2 = pd.melt(poll_data,id_vars=['candidate','party'])

In [248]:
poll_data2.head(30)

                              candidate  ... value
0                     ELANGOVAN.E.V.K.S  ...    19
1                            GURUSAMY.N  ...    14
2                          SATHYABAMA.V  ...   335
3                          SUBBARAYAN.K  ...    12
4                       SENTHILNATHAN.M  ...   337
5                         DINESHKUMAR.N  ...    45
6                           GOPALSAMY.R  ...     2
7   CHAKRAVARTHI RAJA GOPALA KRISHNAN.R  ...     3
8                           SIVAKUMAR.N  ...     1
9                           MURUGESAN.R  ...     5
10                              LAXMI.J  ...     3
11                         SATHYABAMA.R  ...     8
12                        SATHYABHAMA.R  ...     1
13                       SENTHILKUMAR.K  ...     6
14                    SENTHIL KUMAR.T.S  ...     8
15                      SELVABOOPATHI.P  ...    11
16                      DINESHKUMAR.S.K  ...     2
17                        NANDHAKUMAR.R  ...     4
18                         PALANISAMY.M  ...    12
19                  BALASUBRAMANIYAN. P  ...     2
20                          PONNUSAMY.A  ...     7
21                          MURUGAN.R.R  ...     2
22                      MOGHEETH KHAN.A  ...     1
23                          RAJENDRAN.M  ...     2
24                       PASTOR JAMES.A  ...     0
25                      SHEIKDAVOOD.A.M  ...     1
26                                 NOTA  ...     2
27                    ELANGOVAN.E.V.K.S  ...    39
28                           GURUSAMY.N  ...     5
29                         SATHYABAMA.V  ...   360

[30 rows x 4 columns]

In [249]:
poll_data2.rename(columns={'Candidate':'polling Station No.','value':'votes'}, inplace=True)

In [250]:
poll_data2.groupby('candidate')['votes'].sum()

candidate
BALASUBRAMANIYAN. P                      182
CHAKRAVARTHI RAJA GOPALA KRISHNAN.R      398
DINESHKUMAR.N                          36000
DINESHKUMAR.S.K                          275
ELANGOVAN.E.V.K.S                       8628
GOPALSAMY.R                              402
GURUSAMY.N                               933
LAXMI.J                                  189
MOGHEETH KHAN.A                          204
MURUGAN.R.R                             1071
MURUGESAN.R                              408
NANDHAKUMAR.R                            168
NOTA                                    1854
PALANISAMY.M                             774
PASTOR JAMES.A                           245
PONNUSAMY.A                              222
RAJENDRAN.M                              414
SATHYABAMA.R                             221
SATHYABAMA.V                           65256
SATHYABHAMA.R                            232
SELVABOOPATHI.P                          934
SENTHIL KUMAR.T.S                        285
SENTHILKUMAR.K                           408
SENTHILNATHAN.M                        34372
SHEIKDAVOOD.A.M                          195
SIVAKUMAR.N                              238
SUBBARAYAN.K                            2374
Name: votes, dtype: int64

In [251]:
poll_data2.set_index('candidate',drop=True,inplace=True)

In [252]:
poll_data2.head()

                                                      party  ... votes
candidate                                                    ...
ELANGOVAN.E.V.K.S                  INDIAN NATIONAL CONGRESS  ...    19
GURUSAMY.N                              BAHUJAN SAMAJ PARTY  ...    14
SATHYABAMA.V       ALL INDIA ANNA DRAVIDA MUNNETRA KAZHAGAM  ...   335
SUBBARAYAN.K                       COMMUNIST PARTY OF INDIA  ...    12
SENTHILNATHAN.M                   DRAVIDA MUNNETRA KAZHAGAM  ...   337

[5 rows x 3 columns]

In [253]:
poll_data2.to_excel("poll_data_lform2.xlsx")